import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./App.tsx', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // core palette
        navy: '#0D2C6B',
        'navy-dark': '#1A3A6B',
        blue: '#1A5AC8',
        teal: '#00A5C8',
        green: '#22C97A',
        'green-dark': '#00AA66',
        'green-deep': '#1A7A4A',
        orange: '#FF7A1A',
        'orange-dark': '#7A4A00',
        yellow: '#FFD600',
        'yellow-dark': '#997700',
        red: '#FF3B5C',
        'red-dark': '#9B0000',
        'red-deep': '#7A0000',
        'red-light': '#FF6B6B',
        pink: '#D4006A',
        'pink-light': '#FF6B9D',
        'pink-dark': '#8B0050',
        purple: '#9B30FF',
        'purple-dark': '#8B00CC',
        'purple-light': '#BB44FF',
        bronze: '#CD7F32',
        silver: '#C0C0C0',
        'gold-dark': '#AA8800',
        'brown-dark': '#5C3A00',
        'brown-light': '#C87800',
        'brown-deep': '#4A2C00',
        'scheduled-dark': '#3A4060',
        'scheduled-light': '#5566AA',

        // neutrals
        muted: '#8A9BC0',
        gray: '#B0BAD0',
        'gray-slate': '#64748B',
        gbg: '#F2F5FB',
        gl: '#E0E8F5',
        'handle-gray': '#DDE1ED',
        white: '#FFFFFF',

        // semantic bg tints
        'blue-bg': '#E3ECFF',
        'blue-bg-light': '#EEF4FF',
        'green-bg': '#F2FFF8',
        'green-bg-light': '#DFFAEE',
        'green-bg-soft': '#E8F5E9',
        'red-bg': '#FFE3E8',
        'red-bg-light': '#FFF5F5',
        'red-bg-soft': '#FFF0F0',
        'red-border': '#FFD0D0',
        'orange-bg': '#FFF0E3',
        'orange-bg-light': '#FFF0DB',
        'yellow-bg': '#FFFBE6',
        'yellow-amber': '#FFB300',
        'yellow-bg-warm': '#FFF8E3',
        'purple-bg': '#F5EAFF',
        'purple-bg-light': '#F3E8FF',
        'purple-bg-soft': '#EDE9FF',
        'purple-deep': '#6B10DF',
        'teal-bg': '#E0FAFA',
        'pink-bg': '#FFE0F0',
        'green-chip-bg': '#E0F5E0',
        'yellow-chip-bg': '#FFF8E0',

        // overlays
        'overlay-dark': 'rgba(10,15,35,0.65)',
        'navy-alpha-90': 'rgba(13,44,107,0.9)',
      },
      fontFamily: {
        nunito: ['Nunito_800ExtraBold'],
        'nunito-regular': ['Nunito_400Regular'],
        'nunito-semibold': ['Nunito_600SemiBold'],
        'nunito-bold': ['Nunito_700Bold'],
        'nunito-black': ['Nunito_900Black'],
      },
      fontSize: {
        xxs: '9px',
        xs: '10px',
        sm: '11px',
        md: '12px',
        base: '13px',
        lg: '14px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '22px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        full: '999px',
      },
      boxShadow: {
        card: '0px 2px 8px rgba(0,0,0,0.08)',
        header: '0px 4px 12px rgba(0,0,0,0.15)',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
      },
      maxWidth: {
        content: '1200px',
      },
    },
  },
  plugins: [],
};

export default config;
